### ISSUE TITLE
论文中error map 计算

### ISSUE THREAD

**Issue by XiongCaiyu** [Galaxies99/TransCG#11]
非常感谢作者能够开源这个优秀的工作，我这边在数据集上训练了一下网络，我想定性的和作者原文中的Error map 进行一下直观的对比，请问作者能够将论文中绘制error map的代码分享一下吗
![L@@6TSJJI1OV7~ 7D@}({JA](https://user-images.githubusercontent.com/81508910/205048810-eb267d7a-dfc3-42bb-9801-a25a447811dc.png)

**Comment by Galaxies99** [comment]
不好意思 这份代码当时写文章的时候是放在服务器上进行调试的 不过服务器目前出了些问题暂时无法访问。

我印象中代码大致是使用 `matplotlib.pyplot` 里的 `imshow` 绘制的，`cmap` 应该是 `"Reds"`，`vmin` 和 `vmax` 应该分别是 0.0 和 0.35，然后计算error map的时候先忽略 depth 中不合法的 depth （为0的部分），然后将 depth 和 pred 全部 clip 到 [0.3, 1.0] 区间后再进行相减得到 error map。

**Comment by XiongCaiyu** [comment]
感谢您及时的回复，我已经通过你的说明尝试成功了！谢谢！


------------------

火焰族**圣主
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Thursday, Dec 1, 2022 8:26 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Galaxies99/TransCG] 论文中error map 计算 (Issue #11)





 
不好意思 这份代码当时写文章的时候是放在服务器上进行调试的 不过服务器目前出了些问题暂时无法访问。
 
代码大致是使用 matplotlib.pyplot 里的 imshow 绘制的，cmap 应该是 "Reds"，vmin 和 vmax 应该分别是 0.0 和 0.35，然后计算error map的时候先忽略 depth 中不合法的 depth （为0的部分），然后将 depth 和 pred 全部 clip 到 [0.3, 1.0] 区间后再进行相减得到 error map。
