### ISSUE TITLE
非常感谢你的回复，我已经解决这个问题了~

### ISSUE THREAD

**Issue by thk8181** [Galaxies99/TransCG#12]
非常感谢你的回复，我已经解决这个问题了~

_Originally posted by @ZhiyangZhou24 in https://github.com/Galaxies99/TransCG/issues/10#issuecomment-1320860417_

**Comment by thk8181** [comment]
您好，我也遇到了和您同样的问题，加载到一定的位置就会报错，请问您怎么解决的？恳请指点

**Comment by Galaxies99** [comment]
一种是关闭 with_original 选项（设为False）；或者（包含 smooth loss）：修改方法可能有两种：

修改数据集中的原始图片到同一尺寸；
修改loss的时候，不使用原图计算surface normal，使用downsample后的图计算surface normal，不过要注意的是这时候 camera intrinsics也需要根据尺寸变化进行相应调整。

**Comment by Galaxies99** [comment]
另外，可以直接在 Issue #10  中讨论。
