### ISSUE TITLE
Cannot Download Dataset

### ISSUE THREAD

**Issue by Abhijeet-Bhilare** [Galaxies99/TransCG#14]
Hello Team, 
I cannot download dataset from the link --> https://graspnet.net/transcg
I tried using Google Drive but downloading fails after 7-8 GB of file downloads.
I tried on multiple PC's but error persists.
![image](https://user-images.githubusercontent.com/53206992/219572170-c1643e18-7917-4c79-a47b-ad2f9bdbcaf4.png)
Even I tried using Baidu link but I am not able to download from there either.
Please let me if this is possible.

**Comment by Galaxies99** [comment]
Hello,

Does the problem still exist? I tested the download link today and it was fine.

I think it might be a network issue, and I would suggest using some external scripts like `gdown` to download them.

**Comment by Abhijeet-Bhilare** [comment]
Hello team,
Thank you for response and suggestions. 
I could download the dataset now.
