### ISSUE TITLE
Pre-trained checkpoints

### ISSUE THREAD

**Issue by jibweb** [Galaxies99/TransCG#15]
First of all, thanks for releasing your dataset and code !
I was wondering if you would be willing to release the pre-trained weights of the implicit-depth and cleargrasp models trained on TransCG? You mention the results in your paper, and it would be quite helpful !

Thanks

**Comment by Galaxies99** [comment]
Sorry, the pre-trained checkpoints of these two baselines are not saved, but the codebase is modified from their released codes to adapt our TransCG dataset.

**Comment by jibweb** [comment]
Thank you for your quick answer! Where could I find that code adapted to work with your dataset?

**Comment by Galaxies99** [comment]
Just modify the dataset part of their codes according to `dataset/transcg.py`.
