### ISSUE TITLE
关于dataset中transcg.py文件中的数据类型转换

### ISSUE THREAD

**Issue by Jaywen1** [Galaxies99/TransCG#16]
Fang，您好：
       首先十分感谢您贡献性的研究！
       我在运行transcg.py文件 __getitem__函数中读入depth_gt_mask 时， dtype类型为np.uint8，由于transcg数据集中该mask是以float32表示的，这样会导致全0数组，需要*255之后再转为uint8；同样，我查看了cleargrasp.py文件中第87行 depth_gt_mask = np.array(Image.open(self.mask_paths[id]), dtype = np.uint8)，但他的数据集中mask是以0和255表示的，因此不会是全0数组。

**Comment by Galaxies99** [comment]
感谢你的报告！由于最近有点忙，我将在稍晚一些的时间检查这个问题并进行修复。

**Comment by wenzhoulyu** [comment]
您好，这个问题已经修复了嘛

**Comment by Jaywen1** [comment]
> 您好，这个问题已经修复了嘛

不好意思，这个地方是我弄错了，数据集中的mask就是0,1表示，所以用unit8可以，只是两者后处理略微不同。
