### ISSUE TITLE
Annotate grasp pose

### ISSUE THREAD

**Issue by upc-ghy** [Galaxies99/TransCG#17]
Hi, 
Thanks for your great job!
Annotate grasp pose
In your paper, you have set up 240 different viewpoints, so that by annotating the 6 DoF position of the initial viewpoint, you can derive the position of other viewpoints, which greatly saves the labor cost of the annotation work.
Can you explain in detail how you manually annotate the 6 DoF position of each object in the initial viewpoint? And can you elaborate on how you label the grasp 6 DoF pose of each object of the RGB-D image?

**Comment by Galaxies99** [comment]
Hi, thank you for your interest in our work!

The annotation process is illustrated in Fig. 3 in the paper, and you can zoom in to see the detailed steps. The manual annotation step is in subfigure (f). As you can see from Fig. 3f left, we render the 3D model on the camera images, and we can use the keyboard to change the 6DoF pose (e.g., WASD for up, left, down, right; and other keys for rotations of 2 directions of 3 axes)  of the rendered object until the rendered object completely coincides with the real object captured from the camera (which is still during the process), as shown in Fig. 3f right. 

Then, we can establish the transformation between the tracker and the camera, as stated in the paper. So we can change the object position and restart the process again to obtain more precise annotations. On average we repeat the process for 3-5 times.

For your second question, we do not label 6DoF grasp pose on the object in this paper. In this paper, we use a 2-stage strategy: depth completion then grasp detection. We directly adapt the checkpoint of AnyGrasp[1] to perform grasp detection. However, if you want to label 6DoF grasp pose on the object, you can refer to Section 3.3 (grasp pose annotation) from the GraspNet-1billion[2] paper for the detailed process of grasp pose annotation on the 3D models of the objects. Combining the annotated grasps and the 6DoF poses of the object, we can obtain the 6DoF grasp poses of the objects in the scene. Actually, we adapt this method in another paper (see Section 2 of supplementary [3]) which focuses on grasp tracking.

[1] AnyGrasp: https://graspnet.net/anygrasp  
https://ieeexplore.ieee.org/abstract/document/10167687/
[2] https://openaccess.thecvf.com/content_CVPR_2020/papers/Fang_GraspNet-1Billion_A_Large-Scale_Benchmark_for_General_Object_Grasping_CVPR_2020_paper.pdf
[3] https://openaccess.thecvf.com/content/CVPR2023/supplemental/Liu_Target-Referenced_Reactive_Grasping_CVPR_2023_supplemental.pdf
