### ISSUE TITLE
Can you provide a separate mask for each object?

### ISSUE THREAD

**Issue by QiuJunning** [Galaxies99/TransCG#2]
I have to say your work is great! But I wonder if you can provide a separate mask for each object? I have checked your dataset but only found mask for all object.

**Comment by Galaxies99** [comment]
Hello! You may calculate mask for each object from the object pose given in the dataset.

**Comment by QiuJunning** [comment]
> Hello! You may calculate mask for each object from the object pose provided in the dataset.

Thanks！I get it！
