### ISSUE TITLE
深度空缺处的法线计算

### ISSUE THREAD

**Issue by QiuJunning** [Galaxies99/TransCG#20]
非常感谢您的开源工作！我有个关于法线图计算的疑问，很多位置深度图的gt是空缺的，但我发现在法线图里这些像素是有值的，因此想请教下您这块是如何处理的？

![e1159fe88025007aec8798d7e7584f1](https://github.com/Galaxies99/TransCG/assets/82791534/8cbb1578-2f48-423b-8ad7-41bcc46a98dc)
![3f579022d61a5bbfabb2573d2303e10](https://github.com/Galaxies99/TransCG/assets/82791534/57b0699c-d277-4432-b46a-6b560d9c0761)

**Comment by Galaxies99** [comment]
surface normals是直接调用 open3d 中的方法生成的，因此这些位置的surface normals不一定是准的，建议搭配 mask 一起使用，在mask区域内的surface normals是准确的（因为深度信息得到了复原）。
