### ISSUE TITLE
使用realsense D435采集图像并进行透明物体位姿估计时遇到问题

### ISSUE THREAD

**Issue by Gaben21** [Galaxies99/TransCG#21]
您好，我使用Intel Realsense D435相机采集到场景的彩色图像和深度图像，并且将深度图像进行缩放之后输入至inference中进行深度补偿，并输出补全后的深度图像，代码使用是sample_inference.py中的样例，checkpoint使用的是quick start中的所提供的文件。然后将彩色图像和补全后的深度图像输入至graspnet_baseline的demo.py中，最终生成的open3d图像并没有达到补全深度的效果，请问这个是什么原因呢？
![color_1](https://github.com/Galaxies99/TransCG/assets/63099442/c92e26c8-d23c-41ba-ac3b-51d27f490528)
![depth_1](https://github.com/Galaxies99/TransCG/assets/63099442/2102dcd1-8ad9-4f12-8dd1-8ccf64f32ed8)
![open3d](https://github.com/Galaxies99/TransCG/assets/63099442/d36dfb85-1cc8-4c82-9681-ec48ce4c9d23)

**Comment by Galaxies99** [comment]
您好，这个物体的大小比较小，相机获得的关于这个物体的3d数据比较少，同时在数据集中没有出现这个尺度的物品，因此可能难以支持非常精确的补全和抓取。

**Comment by Gaben21** [comment]
好的，谢谢您。那如果想要对这个尺寸的物体进行深度补全的话，自己制作数据集然后再对网络进行训练可以提升效果吗？另外，可以问一下透明物体深度补全的数据集要如何制作呢？

**Comment by Galaxies99** [comment]
对的，这个具体可以参考论文里写的方法。

**Comment by Gaben21** [comment]
> 对的，这个具体可以参考论文里写的方法。

您好，请问您是否可以提供数据集制作的相关代码呢？感谢！

**Comment by GavinYang5** [comment]
@Gaben21 May I ask if your problem has been finally resolved?
