### ISSUE TITLE
实验器材咨询

### ISSUE THREAD

**Issue by xxhaonan** [Galaxies99/TransCG#22]
请问这个白色盘子是在哪里买到的，我们希望搭建一个尽可能和论文一样的实验场景。另外，感谢您的code。
![image](https://github.com/Galaxies99/TransCG/assets/81416871/99a8cc37-4482-4f8c-bce1-3beddd76e6f6)

**Comment by xxhaonan** [comment]
可以提供一下尺寸吗

**Comment by Galaxies99** [comment]
最外侧是800\*600，高度是100，中间workspace是400\*200。单位mm。

**Comment by wenzhoulyu** [comment]
这个盘子是在哪里买的呀
