### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by mk25499** [Galaxies99/TransCG#23]
你好，我想了解在TransCG数据集训练，在 Clear-Real数据集测试的config文件，可以吗？我用这两个数据集做实验RMSE和MAE很高

**Comment by Galaxies99** [comment]
配置文件具体可以参考 configs/320x240 内的设置类似修改。跨域的话可以适当降低lr和训练轮数防止overfit。

**Comment by mk25499** [comment]
> 配置文件具体可以参考 configs/320x240 内的设置类似修改。跨域的话可以适当降低lr和训练轮数防止overfit。

好的，谢谢，您文中展示的用ClearGrasp方法补全TransCG数据集我有点问题请教，ClearGrasp数据集和TransCG数据集格式不太一样，想问下您在使用ClearGrasp代码对TransCG数据集进行补全时：输入的加载以及可视化是怎么做的？我尝试修改ClearGrasp代码但是没有成功。

**Comment by Galaxies99** [comment]
ClearGrasp的training阶段需要的 mask、surface normals 这两块 TransCG 有提供，可以在数据集上进行训练；boundary 的话采用的是 ClearGrasp release 的checkpoint，因为真实世界数据集物体很多，没法逐一手工标注boundary，不像synthetic data可以自动获取label。

**Comment by Galaxies99** [comment]
可视化和用的数据没有关系吧  建议检查一下相机参数等设置是否正确

**Comment by mk25499** [comment]
> 可视化和用的数据没有关系吧 建议检查一下相机参数等设置是否正确

好的，谢谢

**Comment by qwertyshen1001** [comment]
> 你好，我想了解在TransCG数据集训练，在 Clear-Real数据集测试的config文件，可以吗？我用这两个数据集做实验RMSE和MAE很高

你好，请问你解决这个问题了吗，我跨域测试时也遇到了一样的问题。
