### ISSUE TITLE
关于数据收集以及数据集制作的问题

### ISSUE THREAD

**Issue by Gaben21** [Galaxies99/TransCG#24]
您好，非常感谢您的工作。我现在也想尝试制作一个透明物体的相关数据集，请问您是否可以提供数据收集相关的代码呢？如果可以有教程就更好了，十分感谢！

**Comment by Galaxies99** [comment]
数据收集的全部代码已经公开：https://github.com/Galaxies99/TransCG-data-collector/

其中使用的机械臂如文中所述，是Flexiv机械臂。如果需要用其他机械臂采集数据，可能需要自行修改相关代码。

**Comment by Gaben21** [comment]
好的，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hongjie (Tony) ***@***.***&gt;; 
发送时间: 2024年1月21日(星期天) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Galaxies99/TransCG] 关于数据收集以及数据集制作的问题 (Issue #24)





 
数据收集的全部代码已经公开：https://github.com/Galaxies99/TransCG-data-collector/
 
其中使用的机械臂如文中所述，是Flexiv机械臂。如果需要用其他机械臂采集数据，可能需要自行修改相关代码。
