### ISSUE TITLE
关于提供数据集中不同的数据试运行有些异常的问题

### ISSUE THREAD

**Issue by TKroos18** [Galaxies99/TransCG#25]
非常感谢你们的开源工作，这是篇非常好的论文
我在运行sample_inference.py的时候，如果提供scene21场景中1文件夹下的rgb1等数据，读入d435内参数据，可以得到正常的深度补全图
但是在运行rgb2等数据，读入l515内参数据，得到的深度补全图并不正常，画出来的点云是一块平板
![捕获](https://github.com/Galaxies99/TransCG/assets/45529888/5cdfc0c9-612c-4b53-a27e-3705bbc5eb6c)
这是为什么？我是否遗漏了什么步骤？

**Comment by Galaxies99** [comment]
你好！不好意思，由于工作原因刚刚才看到这个issue。

对于L515相机，相机默认的scale factor是4000，而不是D435的1000。因此，需要修改 sample_inference.py 的 L52-L53，将1000修改为4000即可。
