### ISSUE TITLE
how to get mask？

### ISSUE THREAD

**Issue by xklll** [Galaxies99/TransCG#27]
Thank you for your contribution to depth completion of transparent objects. I would like to ask how the mask of transparent objects is obtained? Is it manually annotated or generated by the network?

**Comment by Galaxies99** [comment]
Hi,

For the TransCG dataset, the mask is obtained via semi-autonomous transparent object annotation and tracking.

For the depth completion network, the network does not explicitly generate the mask of transparent objects, or take the mask as input. The masks are only used to calculate the (masked) metrics.
