### ISSUE TITLE
Unexpected shifting from output Pointcloud

### ISSUE THREAD

**Issue by haberger** [Galaxies99/TransCG#4]
Hello,
 
I am a student from Austria. For our undergrad I am currently looking into your work and have encountered an issue.

After installing the requirements I tried running sample_inference.py with the rgb1.png, scene1, folder 1 from the transcg dataset. Unfortunately the results where not what I expected. 

![scene1](https://user-images.githubusercontent.com/74511220/168122121-95852694-d109-427f-a057-bb3e8add1393.png)
What you see here is the output pointcloud in green and the groundtruth pointcloud in red. As you can see the output is slightly shifted in the direction of the camera. 
This is especially an issue since we want to use the output for pose estimation.

I tested some more and used an image from scene 5(folder 0, rgb1.png) and the same phenomenon appeared but amplified. 

![scene5](https://user-images.githubusercontent.com/74511220/168122255-a2d73dbf-b407-4b35-8935-15aee98ce0a6.png)

Is this something you encountered or is there something I am missing? Are there some packages that maybe need a specific version?
Any help would be greatly appreciated.

Thanks a lot!

best regards,
David

**Comment by Galaxies99** [comment]
Hello! 

I checked the scenes that you have mentioned, and this issue indeed occurred. The same model was used for real robot experiments but this situation did not occur at that time (or the shift might be very slight at that time). 

We are looking into this problem currently, and we will keep you informed if there is any progress.

Thank you for your reminding.

**Comment by Galaxies99** [comment]
This bug might be related to issue #5 , and we have fixed it the latest version. The new checkpoint will be released soon.

You might try to train the network from scratch using the new code, this problem would not happen anymore.

Thank you for your reminding.
