### ISSUE TITLE
problems about loading checkpoint

### ISSUE THREAD

**Issue by Nonmy** [Galaxies99/TransCG#6]
Hello, I meet following error when loading provided checkpoint. I use torch.load() with torch1.9.0+cu111. 
`  File "xxx/lib/python3.7/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File 'xxx/lib/python3.7/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.` 
when loading provided checkpoint. I use torch.load() with torch1.9.0+cu111. 
I'm not sure if I conduct wrong loading function or meet a mismatch of torch versions.

**Comment by Galaxies99** [comment]
Hello, I think it might be the version problem. I cannot reproduce the problem in my environment. I would suggest to change torch version and try it again.
