### ISSUE TITLE
The result of depth_res is not good 

### ISSUE THREAD

**Issue by haojieh** [Galaxies99/TransCG#7]
I use the camera realsense D435i to capture the depth_image and color_image from example of IntelRealSense Align & Background Removal.And then,I put depth_image and color_image in to  def inference of class Inferencer but I think the result is not good.Can you tell me where I might be doing wrong?

**Comment by haojieh** [comment]
Thank you for your response! 

1. For 1 point I don't use Background Removal.
2. For 2 point, today I download again.
3. For 3 point,I don't scale the depth previously. I follow your suggestion to scale the depth but the result still same.
4. From 3. I successfully scale the original depth to real depth that values in array are real distance. I think that I am test in the range [0.1, 1.5] because the values of real distance in work space usually 0.4~0.6 meters. But, the values in refine_depth are still same and the values are not real distance.

![image](https://user-images.githubusercontent.com/114550028/192993283-b7d8829d-680c-42c0-9300-6928067ee61d.png)

**Comment by haojieh** [comment]
The picture in left of Align Example is depth_image after scaling, the picture in right of Align Example is refine_depth.Also have a problem is the little black dot which you can see it on the refine_depth.

**Comment by Galaxies99** [comment]
Can you provide the RGBD image you used. I may try to reproduce the problem under my environments.

**Comment by haojieh** [comment]
OK, I will provide the rgb and depth image here. What kind of image do you need? jpg or png?
Also, the close foreground items are gripper. I fix the camera on the robot arm, so you think that black holes are caused by  gripper?By the way, the black holes random move on the refine_depth image.

I list the following questions:
1.I think your network has a way to measure the depth of transparent objects but at the moment even scenes without transparent objects are wrong depth information.
2.Why reason cause the black holes?
If you need more information about my environment please tell me.
Thank you!

**Comment by Galaxies99** [comment]
OK, we will continue the discussions with E-mail.

**Comment by mtbui2010** [comment]
Hi Fang.
I appreciate your work. 
I have the same problem with the above issue. Did you find a solution? Can you share the solution?

**Comment by Galaxies99** [comment]
The problem has been greatly reduced in the new version of code and checkpoint.

In the new version, the shifting problem is slight, _i.e._, only ~2cm, which can be solved using engineering approaches, such as subtract 1cm for all depth map (this can be varied under different circumstances, but under our test the shifting problem is slight compared to the original problem).

In the new version, you can also use `depth_coefficient` to control the filling of invalid pixels in the inference stage, see L55 in `sample_inference.py`. If you find empty hole/black hole in the depth map, I would suggest to decrease the value of `depth_coefficient` to solve it.

Thanks for reporting problems!

**Comment by ZhiyangZhou24** [comment]
> The problem has been greatly reduced in the new version of code and checkpoint.
> 
> In the new version, the shifting problem is slight, _i.e._, only ~2cm, which can be solved using engineering approaches, such as subtract 1cm for all depth map (this can be varied under different circumstances, but under our test the shifting problem is slight compared to the original problem).
> 
> In the new version, you can also use `depth_coefficient` to control the filling of invalid pixels in the inference stage, see L55 in `sample_inference.py`. If you find empty hole/black hole in the depth map, I would suggest to decrease the value of `depth_coefficient` to solve it.
> 
> Thanks for reporting issues!
Hi Fang.
I appreciate your work.I have the same problem with the above issue(shifting&hole problems). And I tried your latest uploaded code and Checkpoint today, but I encountered the following problem, is it because the Checkpoint I am using is not the latest? Can you upload the latest Checkpoint? Thanks!

**Comment by Galaxies99** [comment]
> Hi Fang. I appreciate your work.I have the same problem with the above issue(shifting&hole problems). And I tried your latest uploaded code and Checkpoint today, but I encountered the following problem, is it because the Checkpoint I am using is not the latest? Can you upload the latest Checkpoint? Thanks! `Traceback (most recent call last): File "/home/lab/TransCG/sample_inference.py", line 47, in <module> inferencer = Inferencer() File "/home/lab/zzy/TransCG/inference.py", line 61, in __init__ self.model.load_state_dict(checkpoint['model_state_dict']) File "/home/lab/anaconda3/envs/transcg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict self.__class__.__name__, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for DFNet: size mismatch for final.3.weight: copying a param with shape torch.Size([1, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).`

Hi, the checkpoint is the latest, and you also need to update the source code.

I slightly change the last layer of the model (from kernel = 3 to kernel = 1) for performance improvement.

**Comment by Galaxies99** [comment]
Solved during e-mail conversation with @haojieh. Thus, mark this issue as closed. 

For further questions, please add new issues and describe your questions.
