### ISSUE TITLE
推理得到的深度图与paper中相比差别较大

### ISSUE THREAD

**Issue by ZhiyangZhou24** [Galaxies99/TransCG#9]
非常感谢作者能够开源这个工作。我在采用最新的code和checkoint进行推理时发现深度补全网络并没有达到论文中的效果，我用作者论文中的Scene56和Scene1这2个场景进行推理测试，发现补全之后的深度与论文中差距较大，请问我要怎么调试参数才能够复现论文中的效果呢，非常感谢

**Comment by Galaxies99** [comment]
我们新release的checkpoint在metrics上比之前的checkpoint提高了一些，可以参考 assets/docs/DFNet.md；这个可以直接通过test.py进行验证。

另外，论文中inference的结果你可以通过我们release的旧版本checkpoint和代码进行验证，那些图是直接通过旧版本模型得到的。新训练的版本的模型与旧版本的模型生成效果会有差异，但我这里感觉差别不是很大；你可以通过调整 sample inference 里的 depth coefficient参数来调整outlier的范围来生成更加稳定的depth。

这里附上新模型scene21和scene56的生成效果（论文中提到的两个场景）
![scene21-view1-cam1-depth](https://user-images.githubusercontent.com/48870052/195790573-4b40eab1-3d03-4286-88f6-860a2b57096a.png)
![scene56-view1-cam1-depth](https://user-images.githubusercontent.com/48870052/195790594-7fe2beee-b483-48c0-b939-3416d3093329.png)
以及对应的ground-truth
![scene21-view1-cam1-depth-gt](https://user-images.githubusercontent.com/48870052/195790639-73fd0f7e-fda6-4421-b038-71354dd55edd.png)
![scene56-view1-cam1-depth-gt](https://user-images.githubusercontent.com/48870052/195790668-01fc3682-d82b-401f-982f-c17810236713.png)

**Comment by ZhiyangZhou24** [comment]
非常感谢你的回复，我这边并没有计算err_map，下面是我用最新release的code和checkpoint推理出来的scene21和scene56的效果，我使用_depthcoefficient=3_，其余的设置均为默认值，推理出来的深度图中会存在大面积的“污渍”（一些black hole），和你回复中的结果还是有些差距的，请问这是什么原因导致的呢？
![scene56](https://user-images.githubusercontent.com/39725984/195805115-2cb0bf15-b87a-48ac-aa50-3e690d29506e.png)
![scene21](https://user-images.githubusercontent.com/39725984/195805139-7a04d057-416e-4ca5-be74-604c31dc9061.png)

**Comment by Galaxies99** [comment]
不好意思，我检查了一下，我上传了错误版本的checkpoint。马上会更新正确版本的checkpoint，感谢报告问题！

**Comment by ZhiyangZhou24** [comment]
非常感谢你能这么即时的回复并解决这个问题，我这边已经测试了你最新发布的checkpoint，得到了新模型预期的效果。

**Comment by Galaxies99** [comment]
> 非常感谢你能这么即时的回复并解决这个问题，我这边已经测试了你最新发布的checkpoint，得到了新模型预期的效果。

也感谢你对我们work的关注！

**Comment by Qiqiqi1123** [comment]
您好，想请教这个图片处理用了哪种处理方式，我使用了JET 但是效果不理想。
